version: "3.8"
services:
  db:
    container_name: db-decks
    image: postgres:14.2-alpine3.15
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - decks
    ports:
      - "${DB_PORT}:5432"

  server:
    container_name: server-decks
    build:
      context: .
      dockerfile: build/docker/Dockerfile.dev
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    networks:
      - decks

volumes:
  db-data:
    driver: local

networks:
  decks:
    driver: bridge
